openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8080'
paths:
  /api/ver:
    get:
      summary: バージョン一覧取得
      description: バージョン一覧の情報を返却する
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '200'
          content:
            text/plain:
              schema:
                type: string
                example: "{\n \"result\": true,\n \"version\": \"v1.0.1\",\n \"min_version\": \"v1.0.1\""
      tags:
        - Endpoints
      security: []
