FROM mysql@sha256:897086d07d1efa876224b147397ea8d3147e61dd84dce963aace1d5e9dc2802d

ENV TZ=UTC \
  MYSQL_DATABASE=onlineprescribe \
  MYSQL_USER=onlineprescribe \
  MYSQL_PASSWORD=onlineprescribe1234 \
  MYSQL_ROOT_PASSWORD=onlineprescribe1234

COPY ./my.cnf /etc/my.cnf
