<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersubsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ordersubs')->delete();
        
        \DB::table('ordersubs')->insert(array (
            0 => 
            array (
                'ordersub_id' => 1,
                'order_id' => 1,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 46,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 06:37:20',
                'ordersub_updated' => '2020-08-10 14:30:17',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'ordersub_id' => 2,
                'order_id' => 2,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 8,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 2,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 10:35:52',
                'ordersub_updated' => '2020-05-12 10:48:54',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'ordersub_id' => 3,
                'order_id' => 3,
                'product_id' => 147,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 47,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 2,
                'ordersub_price' => 47520,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 10:40:41',
                'ordersub_updated' => '2020-05-12 10:48:54',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'ordersub_id' => 4,
                'order_id' => 4,
                'product_id' => 120,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 57,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 1000,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 0,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 17:04:23',
                'ordersub_updated' => '2020-08-10 14:30:12',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'ordersub_id' => 5,
                'order_id' => 4,
                'product_id' => 148,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 59,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 60720,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 17:04:23',
                'ordersub_updated' => '2020-10-05 23:32:52',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'ordersub_id' => 6,
                'order_id' => 5,
                'product_id' => 152,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 63,
                'coupon_id' => 0,
                'reason_id' => 3,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 17:06:30',
                'ordersub_updated' => '2021-05-30 20:00:30',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'ordersub_id' => 7,
                'order_id' => 6,
                'product_id' => 152,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 66,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-11 17:11:56',
                'ordersub_updated' => '2020-10-06 00:29:05',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'ordersub_id' => 8,
                'order_id' => 7,
                'product_id' => 148,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 72,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 2,
                'ordersub_price' => 60720,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-12 10:48:54',
                'ordersub_updated' => '2020-05-12 13:54:33',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'ordersub_id' => 9,
                'order_id' => 8,
                'product_id' => 120,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 80,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 1,
                'ordersub_price' => 1000,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 0,
                'ordersub_lastsub' => '2022-03-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-12 13:53:58',
                'ordersub_updated' => '2022-03-01 00:03:01',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'ordersub_id' => 10,
                'order_id' => 9,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 81,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 2,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-12 13:54:33',
                'ordersub_updated' => '2020-05-18 13:29:27',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'ordersub_id' => 11,
                'order_id' => 10,
                'product_id' => 152,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 83,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 2,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-05-18 13:29:27',
                'ordersub_updated' => '2020-06-12 15:14:32',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'ordersub_id' => 12,
                'order_id' => 12,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 109,
                'coupon_id' => 0,
                'reason_id' => 9,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => 'aaa',
                'ordersub_created' => '2020-06-12 15:14:32',
                'ordersub_updated' => '2021-06-10 15:58:45',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'ordersub_id' => 13,
                'order_id' => 13,
                'product_id' => 148,
                'category_id' => 0,
                'customer_id' => 2,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 110,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 1,
                'ordersub_price' => 60720,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2022-03-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-06-15 12:22:02',
                'ordersub_updated' => '2022-03-01 00:03:01',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'ordersub_id' => 14,
                'order_id' => 17,
                'product_id' => 120,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 131,
                'coupon_id' => 0,
                'reason_id' => 4,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 1000,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 0,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-09-15 03:27:03',
                'ordersub_updated' => '2021-05-30 20:03:20',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'ordersub_id' => 15,
                'order_id' => 18,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 5,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 132,
                'coupon_id' => 0,
                'reason_id' => 9,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2021-06-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-09-15 10:05:37',
                'ordersub_updated' => '2021-06-02 12:12:32',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'ordersub_id' => 16,
                'order_id' => 19,
                'product_id' => 120,
                'category_id' => 0,
                'customer_id' => 5,
                'user_id' => 23,
                'branch_id' => 1,
                'cart_id' => 133,
                'coupon_id' => 0,
                'reason_id' => 9,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 1000,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 0,
                'ordersub_lastsub' => '2021-06-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-09-15 14:33:10',
                'ordersub_updated' => '2021-06-02 12:16:32',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'ordersub_id' => 17,
                'order_id' => 26,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 4,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 145,
                'coupon_id' => 0,
                'reason_id' => 2,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2021-06-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-10-09 15:06:11',
                'ordersub_updated' => '2021-06-02 11:59:24',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'ordersub_id' => 18,
                'order_id' => 29,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 1,
                'user_id' => 1,
                'branch_id' => 1,
                'cart_id' => 148,
                'coupon_id' => 0,
                'reason_id' => 9,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2021-05-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2020-10-14 10:26:00',
                'ordersub_updated' => '2021-05-30 22:40:22',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'ordersub_id' => 19,
                'order_id' => 48,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 7,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 195,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 0,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 7,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2021-05-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2021-02-04 11:48:48',
                'ordersub_updated' => '2021-05-29 01:41:11',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'ordersub_id' => 20,
                'order_id' => 66,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 23,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 230,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 32560,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2021-08-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2021-06-22 12:33:38',
                'ordersub_updated' => '2021-08-11 14:54:50',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'ordersub_id' => 21,
                'order_id' => 81,
                'product_id' => 147,
                'category_id' => 0,
                'customer_id' => 23,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 251,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 47520,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 3,
                'ordersub_price' => 47520,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2021-08-11 14:54:50',
                'ordersub_updated' => '2021-10-29 15:49:16',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'ordersub_id' => 22,
                'order_id' => 0,
                'product_id' => 111,
                'category_id' => 0,
                'customer_id' => 32,
                'user_id' => 50,
                'branch_id' => 1,
                'cart_id' => 287,
                'coupon_id' => 0,
                'reason_id' => 0,
                'ordersub_original' => 32560,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 1,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 0,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '2022-03-01',
                'ordersub_reason' => '',
                'ordersub_created' => '2021-10-29 15:32:42',
                'ordersub_updated' => '2022-03-01 00:03:01',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
            22 => 
            array (
                'ordersub_id' => 23,
                'order_id' => 106,
                'product_id' => 111,
                'category_id' => 1,
                'customer_id' => 30,
                'user_id' => 32,
                'branch_id' => 1,
                'cart_id' => 302,
                'coupon_id' => 0,
                'reason_id' => 7,
                'ordersub_original' => 32560,
                'ordersub_discount' => 0,
                'ordersub_income' => 0,
                'ordersub_couponprice' => 0,
                'ordersub_status' => 5,
                'ordersub_price' => 32560,
                'ordersub_extaxprice' => 29600,
                'ordersub_paymethod' => 1,
                'ordersub_booking' => 1,
                'ordersub_lastsub' => '0000-00-00',
                'ordersub_reason' => '',
                'ordersub_created' => '2022-03-10 14:19:05',
                'ordersub_updated' => '2022-03-10 14:51:55',
                'ordersub_deleted' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}