<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('profiles')->delete();
        
        \DB::table('profiles')->insert(array (
            0 => 
            array (
                'profile_id' => 1,
                'user_id' => 1,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
            'profile_sportnames' => 'あり(スポーツ)',
            'profile_worrying' => '肩こり,むくみ()',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2020-05-01 11:41:50',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            1 => 
            array (
                'profile_id' => 2,
                'user_id' => 1,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,その他',
                'profile_otherworries' => '悩みある',
                'profile_size' => 'L',
                'profile_weight' => 50,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-05-05 04:55:18',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            2 => 
            array (
                'profile_id' => 3,
                'user_id' => 1,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 1,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,その他',
                'profile_otherworries' => '悩みある',
                'profile_size' => 'L',
                'profile_weight' => 50,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-05-05 04:56:05',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            3 => 
            array (
                'profile_id' => 4,
                'user_id' => 1,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,その他',
                'profile_otherworries' => '悩みある',
                'profile_size' => 'L',
                'profile_weight' => 50,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-05-05 04:56:13',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            4 => 
            array (
                'profile_id' => 5,
                'user_id' => 1,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,その他',
                'profile_otherworries' => '悩みある',
                'profile_size' => 'L',
                'profile_weight' => 50,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-05-05 04:56:19',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            5 => 
            array (
                'profile_id' => 6,
                'user_id' => 32,
                'customer_id' => 2,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '膝痛,姿勢が悪い',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2020-05-08 12:27:11',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            6 => 
            array (
                'profile_id' => 7,
                'user_id' => 23,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,その他',
                'profile_otherworries' => '悩みある',
                'profile_size' => 'L',
                'profile_weight' => 50,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-08-30 18:32:46',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            7 => 
            array (
                'profile_id' => 8,
                'user_id' => 23,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,その他',
                'profile_otherworries' => '悩みある',
                'profile_size' => 'L',
                'profile_weight' => 55,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-08-30 18:35:15',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            8 => 
            array (
                'profile_id' => 9,
                'user_id' => 23,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 55,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-08-30 18:35:38',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            9 => 
            array (
                'profile_id' => 10,
                'user_id' => 23,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 55,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-08-30 21:25:00',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            10 => 
            array (
                'profile_id' => 11,
                'user_id' => 23,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'テニス',
                'profile_worrying' => '肩こり,むくみ,腰痛,便秘,冷え症',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 55,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-08-31 01:47:40',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            11 => 
            array (
                'profile_id' => 12,
                'user_id' => 23,
                'customer_id' => 1,
                'purpose_id' => 3,
                'profile_target' => 'テスト目標',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '肩こり,むくみ,腰痛,便秘,冷え症',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 55,
                'profile_fat' => 80,
                'profile_muscles' => 20,
                'profile_created' => '2020-08-31 01:47:53',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            12 => 
            array (
                'profile_id' => 13,
                'user_id' => 32,
                'customer_id' => 5,
                'purpose_id' => 4,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2020-09-15 10:03:03',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            13 => 
            array (
                'profile_id' => 14,
                'user_id' => 35,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71,
                'profile_fat' => 34,
                'profile_muscles' => 26,
                'profile_created' => '2020-11-21 15:20:39',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            14 => 
            array (
                'profile_id' => 15,
                'user_id' => 1,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71000,
                'profile_fat' => 3400,
                'profile_muscles' => 2600,
                'profile_created' => '2020-11-22 05:26:07',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            15 => 
            array (
                'profile_id' => 16,
                'user_id' => 1,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71100,
                'profile_fat' => 3400,
                'profile_muscles' => 2600,
                'profile_created' => '2020-11-22 05:26:17',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            16 => 
            array (
                'profile_id' => 17,
                'user_id' => 1,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71100,
                'profile_fat' => 3400,
                'profile_muscles' => 2600,
                'profile_created' => '2020-11-22 05:26:22',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            17 => 
            array (
                'profile_id' => 18,
                'user_id' => 1,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71125,
                'profile_fat' => 3400,
                'profile_muscles' => 2600,
                'profile_created' => '2020-11-22 05:26:31',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            18 => 
            array (
                'profile_id' => 19,
                'user_id' => 1,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71125,
                'profile_fat' => 3435,
                'profile_muscles' => 2600,
                'profile_created' => '2020-11-22 05:26:52',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            19 => 
            array (
                'profile_id' => 20,
                'user_id' => 1,
                'customer_id' => 8,
                'purpose_id' => 1,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'バスケ',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 71125,
                'profile_fat' => 3435,
                'profile_muscles' => 2625,
                'profile_created' => '2020-11-22 05:26:59',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            20 => 
            array (
                'profile_id' => 21,
                'user_id' => 35,
                'customer_id' => 9,
                'purpose_id' => 4,
                'profile_target' => '体力つけたい',
                'profile_diet' => 0,
                'profile_exercise' => 1,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '肩こり,膝痛,腰痛,冷え症',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 64700,
                'profile_fat' => 4110,
                'profile_muscles' => 2050,
                'profile_created' => '2020-11-28 23:58:39',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            21 => 
            array (
                'profile_id' => 22,
                'user_id' => 35,
                'customer_id' => 10,
                'purpose_id' => 1,
                'profile_target' => 'メリハリのある身体',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'ヨガ',
                'profile_worrying' => '肩こり,むくみ,O脚・X脚,腰痛',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 56300,
                'profile_fat' => 3150,
                'profile_muscles' => 2090,
                'profile_created' => '2020-12-19 15:46:15',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            22 => 
            array (
                'profile_id' => 23,
                'user_id' => 35,
                'customer_id' => 11,
                'purpose_id' => 1,
                'profile_target' => '健康になる',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'ヨガ',
                'profile_worrying' => '肩こり,腰痛',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 64300,
                'profile_fat' => 3700,
                'profile_muscles' => 2190,
                'profile_created' => '2020-12-19 15:52:30',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            23 => 
            array (
                'profile_id' => 24,
                'user_id' => 35,
                'customer_id' => 12,
                'purpose_id' => 2,
                'profile_target' => 'ヒップアップ',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 1,
                'profile_sports' => 0,
                'profile_nosports' => 1,
                'profile_sportnames' => '',
                'profile_worrying' => '肩こり,腰痛,冷え症',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 45900,
                'profile_fat' => 2130,
                'profile_muscles' => 400,
                'profile_created' => '2020-12-19 15:59:12',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            24 => 
            array (
                'profile_id' => 25,
                'user_id' => 35,
                'customer_id' => 13,
                'purpose_id' => 2,
                'profile_target' => 'マイナス10kg',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 1,
                'profile_sportnames' => '',
                'profile_worrying' => '膝痛',
                'profile_otherworries' => '',
                'profile_size' => 'LL',
                'profile_weight' => 73900,
                'profile_fat' => 4280,
                'profile_muscles' => 2290,
                'profile_created' => '2020-12-19 16:04:17',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            25 => 
            array (
                'profile_id' => 26,
                'user_id' => 23,
                'customer_id' => 18,
                'purpose_id' => 3,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'LL',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-01-28 15:37:47',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            26 => 
            array (
                'profile_id' => 27,
                'user_id' => 23,
                'customer_id' => 19,
                'purpose_id' => 3,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'サッカー',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-01-28 22:33:40',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            27 => 
            array (
                'profile_id' => 28,
                'user_id' => 32,
                'customer_id' => 20,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-02-03 12:29:07',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            28 => 
            array (
                'profile_id' => 29,
                'user_id' => 32,
                'customer_id' => 21,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => 'サッカー',
                'profile_worrying' => '肩こり,腰痛,便秘,冷え症,姿勢が悪い',
                'profile_otherworries' => '',
                'profile_size' => 'S',
                'profile_weight' => 61000,
                'profile_fat' => 500,
                'profile_muscles' => 3200,
                'profile_created' => '2021-02-03 12:41:20',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            29 => 
            array (
                'profile_id' => 30,
                'user_id' => 23,
                'customer_id' => 22,
                'purpose_id' => 3,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-02-03 13:00:23',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            30 => 
            array (
                'profile_id' => 31,
                'user_id' => 32,
                'customer_id' => 23,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'S',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-04-22 14:50:44',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            31 => 
            array (
                'profile_id' => 32,
                'user_id' => 32,
                'customer_id' => 25,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'S',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-08-10 14:36:57',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            32 => 
            array (
                'profile_id' => 33,
                'user_id' => 50,
                'customer_id' => 26,
                'purpose_id' => 4,
                'profile_target' => '',
                'profile_diet' => 1,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 1,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '肩こり,腰痛',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 60500,
                'profile_fat' => 2050,
                'profile_muscles' => 2890,
                'profile_created' => '2021-10-15 14:56:46',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            33 => 
            array (
                'profile_id' => 34,
                'user_id' => 32,
                'customer_id' => 28,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'M',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-10-22 17:42:20',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            34 => 
            array (
                'profile_id' => 35,
                'user_id' => 32,
                'customer_id' => 29,
                'purpose_id' => 4,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'L',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-10-22 17:53:24',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            35 => 
            array (
                'profile_id' => 36,
                'user_id' => 32,
                'customer_id' => 30,
                'purpose_id' => 3,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'LL',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-10-22 17:56:17',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
            36 => 
            array (
                'profile_id' => 37,
                'user_id' => 50,
                'customer_id' => 31,
                'purpose_id' => 1,
                'profile_target' => '',
                'profile_diet' => 0,
                'profile_exercise' => 0,
                'profile_nodiet' => 0,
                'profile_sports' => 0,
                'profile_nosports' => 0,
                'profile_sportnames' => '',
                'profile_worrying' => '',
                'profile_otherworries' => '',
                'profile_size' => 'S',
                'profile_weight' => 0,
                'profile_fat' => 0,
                'profile_muscles' => 0,
                'profile_created' => '2021-10-29 14:45:56',
                'profile_updated' => '0000-00-00 00:00:00',
                'profile_deleted' => '0000-00-00 00:00:00',
            ),
        ));
        
        
    }
}